name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pytests:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t", "pypy-3.11"]
        exclude:
          - os: windows-latest
            python-version: "pypy-3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: python -m pip install --upgrade pip
      - run: pip install pytest pytest-asyncio
      - run: pip install --editable .
      - run: pytest
  doc_format:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - run: python -m pip install --upgrade pip
      - run: python -m pip install 'readme-renderer[md]'
      - run: python -m readme_renderer README.rst -o /dev/null
      - run: python -m readme_renderer README_JP.rst -o /dev/null
      - run: python -m readme_renderer CHANGES.rst -o /dev/null
